Tp3/Models/Concert.cs
using System.ComponentModel.DataAnnotations;

namespace Tp3.Models
{
    public class Concerts
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Type is required.")]
        public string Type { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Date is required.")]
        public DateTime Date { get; set; }

        public Concerts(int id, string name, string type, DateTime date)
        {
            Id = id;
            Name = name;
            Type = type;
            Date = date;
        }

        public Concerts()
        {
        }
    }

}
    

    

Tp3/Models/ErrorViewModel.cs
namespace Tp3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tp3/Models/InventoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Tp3.Models
{
    public class InventoryContext:DbContext

    {
        public InventoryContext(DbContextOptions<InventoryContext> options) : base(options) { } 

        public DbSet<Concerts> Concerts { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.Entity<Concerts>();

        }
    
    }
}

Tp3/Controllers/ConcertsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using MySql.Data.MySqlClient;
using Tp3.Models;
using Microsoft.EntityFrameworkCore;

namespace Tp3.Controllers
{
    public class ConcertsController : Controller
    {
        private readonly ILogger<ConcertsController> _logger;
        private readonly InventoryContext _db;

        public ConcertsController(ILogger<ConcertsController> logger, InventoryContext db)
        {
            _db = db;
            _logger = logger;

        }

        public async Task<IActionResult> Index()
        {

            var result = await _db.Concerts.ToListAsync();

            return View(result);
        }


        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Concerts contact)
        {
            if (ModelState.IsValid)
            {
                _db.Concerts.Add(contact);
                await _db.SaveChangesAsync();
                TempData["success"] = "Création effectuée avec succès";
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var contact = await _db.Concerts.FindAsync(id);

            if (contact == null)
            {
                return NotFound();
            }


            return View(contact);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

       
        public async Task<IActionResult> Edit(Concerts contact, int id)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Concerts.Update(contact);
                await _db.SaveChangesAsync();
                TempData["success"] = "Mise à jour effectuée avec succès";
                return RedirectToAction("Index");
            }
            return View(contact);
        }
       

        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var contact = await _db.Concerts.FindAsync(id);

            if (contact == null)
            {
                return NotFound();
            }

            _db.Concerts.Remove(contact);
            await _db.SaveChangesAsync();
            TempData["success"] = "Suppresson effectué avec succès";
            return RedirectToAction("Index");



        }

    }
}

Tp3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Tp3.Controllers
{
    public class HomeController : Controller
    {
        public string Index()
        {
            return "hello etudiant fia3 issat sousse";
        }
    }
}

Tp3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Tp3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Tp3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tp3.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Tp3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Tp3.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Tp3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tp3/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tp3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tp3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Tp3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Tp3 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tp3/Views/Concerts/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Concerts;
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="Name" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type">Type</label>
        <input asp-for="Type" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="Type" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Date" class="control-label"></label>
        <input asp-for="Date" class="form-control" asp-format="{0:dd.MM.yyyy hh:mm}">


    </div>

    <button type="submit" class="btn btn-primary" value="Create">Ajouter</button>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Tp3/Views/Concerts/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Concerts;
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div class="form-group">
        <label asp-for="Name">Nom</label>
        <input asp-for="Name" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="Name" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type">Type</label>
        <input asp-for="Type" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="Type" class="form-text text-danger"></span>
    </div>
   
    <div class="form-group">
        <label asp-for="Date" class="control-label">Date</label>
        <input asp-for="Date" class="form-control" asp-format="{0:dd.MM.yyyy hh:mm}">
    </div>
    <button type="submit" class="btn btn-primary" value="Create">Edit</button>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Tp3/Views/Concerts/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Concerts>
<div>
    <div><a class="btn btn-primary mb-2" asp-controller="Concerts" asp-action="Create">New Concert</a></div>
</div>
<table class="table">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Type</th>
        <th scope="col" >Date</th>
        <th scope="col">Actions</th>
    </tr>

    @foreach (var concert in Model)
    {
        <tr scope="raw">
            <td >@concert.Name </td>
            <td >@concert.Type</td>
            <td >@concert.Date</td>
            <td>
                @{
                    var modal = "#id"+ @concert.Id.ToString();
                    var id ="id"+ @concert.Id.ToString();
                    Console.WriteLine(modal +"this is the id" + id);
                }
                
                <a class="btn btn-warning" asp-controller="Concerts" asp-action="Edit" asp-route-id="@concert.Id"><i class="bi bi-pencil-square"></i></a>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target=@modal><i class="bi bi-trash-fill"></i></button>

                <div class="modal fade" id=@id tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header"><h5 class="modal-title" id="exampleModalLabel">Deleting concert... </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">Do you want to delete <b> @concert.Name</b> concert  ?</div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                <a asp-controller="Concerts" asp-action="Delete" asp-route-id="@concert.Id" class="btn btn-primary">Valider</a>
                            </div>
                        </div>
                    </div>
                </div>

            </td>

        </tr>
    }
</table>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#id1">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="id1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Tp3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tp3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_MVC</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Concerts" asp-action="Index">Tunis Concert</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Tp3 .net<a asp-area="" asp-controller="Concerts" asp-action="Index">CRUD ASP.NET Core</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>